### ISSUE TITLE
Manage Firefox dark mode

### ISSUE THREAD

**Issue by rubenvar** [rubenvar/csv-reader#9]
Firefox auto detects dark mode preference in the browser and adds:

```css
:root {
  background: #2a2a2e;
  color: rgb(249, 249, 250);
}
```

This messes up the table styling, because I don't set default styles for these values.

- Quick fix: hard code styles that overwrite the defult ones in `:root`:
  ```css
  :root {
    background: #fff;
    color: #000;
  }
  ```
- Better fix: add a dark mode to the extension (I'm already adding some dark styles when _rainbow-coloring_), and auto-detect user config.
